export const COLLAPSED = 'COLLAPSED';
export const SET_STORE_VALUE = 'SET_STORE_VALUE';
export const ADD_NEW_ROW = 'ADD_NEW_ROW';
export const ROW_CHANGED = 'ROW_CHANGED';

export const GET_SUCCESS_IMAGES = 'GET_SUCCESS_IMAGES';
export const SET_TV_TEMPLATE = 'SET_TV_TEMPLATE';
export const GET_SUCCESS_SHOPS = 'GET_SUCCESS_SHOPS';